[build]
  command = "npm run build -- --configuration production"
  publish = "dist/sign-translate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PORT = "3000"
  NODE_ENV = "production"

[dev]
  command = "npm run start"
  port = 3000
