[build]
  base = "/"
  command = "npm run build"
  publish = "dist/sign-translate/browser"

[build.environment]
  PORT = "3000"
  NODE_ENV = "production"

[dev]
  command = "npm run start"
  port = 3000
