[build]
  command = "npm install && ./node_modules/.bin/ng build --configuration=production"
  publish = "dist/sign-translate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PORT = "3000"
  NODE_ENV = "production"
  NODE_VERSION = "20"

[dev]
  command = "npm run start"
  port = 3000
