services:
  - type: web
    name: sign-translate
    env: node
    buildCommand: |
      npm install -g npm@10.0.0
      npm install
      npm install @angular/cli@19.2.5 @angular-devkit/build-angular@19.2.5
      npm run build
    startCommand: npx serve -s dist/sign-translate -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.0.0
      - key: NPM_VERSION
        value: 10.0.0
    healthCheckPath: /
    autoDeploy: true
    plan: free
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 