services:
  - type: web
    name: sign-translate
    env: node
    buildCommand: npm install && npm install @angular/cli@19.2.5 @angular-devkit/build-angular@19.2.5 && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /healthz
    autoDeploy: true 